### PR TITLE
Embedded CSS in seaborn table html file

### PR DESCRIPTION
**Pull request by christensonb**
This change is [Reviewable](https://reviewable.io/reviews/seaborngames/table/44)

### CODE REVIEW

**Comment by MichaelChristenson** [comment]
___
*[seaborn_table/table.py, line 2513 at r2](https://reviewable.io/reviews/seaborngames/table/44#-MUtFSjAB4DD6MAkBovw:-MUtFSjAB4DD6MAkBovx:bghmvn9) ([raw file](https://github.com/seaborngames/table/blob/196da39f6aaf3a9cc089f6ee253bb81850b3c242/seaborn_table/table.py#L2513)):*
> ```Python
>             head = '<th rowspan="%s"' % cell.count
> 
>         if cell is None or cell == '':
> ```

Not "if not cell:"?

**Review by MichaelChristenson — COMMENTED** [review]
> Reviewed 16 of 20 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/seaborngames/table/44)* status: 18 of 20 files reviewed, all discussions resolved (waiting on @christensonb)

**Review by MichaelChristenson — APPROVED** [review]
> Reviewed 2 of 20 files at r1.
> *[Reviewable](https://reviewable.io/reviews/seaborngames/table/44)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @christensonb)

**Review by christensonb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/seaborngames/table/44)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @christensonb)

___
*[seaborn_table/table.py, line 2513 at r2](https://reviewable.io/reviews/seaborngames/table/44#-MUtFSjAB4DD6MAkBovw:-MUtz0Vp0MIhAeSE7pkd:b-2u6gyc) ([raw file](https://github.com/seaborngames/table/blob/196da39f6aaf3a9cc089f6ee253bb81850b3c242/seaborn_table/table.py#L2513)):*
<details><summary><i>Previously, MichaelChristenson wrote…</i></summary><blockquote>

Not "if not cell:"?
</blockquote></details>

that would not account for cell value of 0 which I want

**Pull request merged**
