### PR TITLE
prototype new column_index

### PR DESCRIPTION
**Pull request by christensonb**

### CODE REVIEW

**Comment by MichaelChristenson** [comment]
It seems that this commit is largely based around renaming certain variables.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/seaborngames/table/1#-:-L1OXKHGFtdUFfIBKkYv:b-pal78n)*

**Comment by MichaelChristenson** [comment]
No large issues seem to be present.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/seaborngames/table/1#-:-L1OXYebrOXJjv0na4J4:b-csmpxy)*

**Comment by MichaelChristenson** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/seaborngames/table/1)*

**Comment by MichaelChristenson** [comment]
*[seaborn/seaborn_table.py, line 681 at r1](https://reviewable.io:443/reviews/seaborngames/table/1#-L1OdRZlrvx0D2I1VAhs:-L1OdRZlrvx0D2I1VAht:bxt5wlj) ([raw file](https://github.com/seaborngames/table/blob/5e51d53a6236f6dcd19a64057fa3ae943587905e/seaborn/seaborn_table.py#L681)):*
> ```Python
> 
>         if item not in self.row_columns:
>             self.row_columns = self.row_columns + [item]
> ```

Change to "self.row_columns+=[item]"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seaborngames/table/1)*

**Comment by christensonb** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[seaborn/seaborn_table.py, line 681 at r1](https://reviewable.io:443/reviews/seaborngames/table/1#-L1OdRZlrvx0D2I1VAhs:-L1mcgY3jguRmExTgrCD:b-896fix) ([raw file](https://github.com/seaborngames/table/blob/5e51d53a6236f6dcd19a64057fa3ae943587905e/seaborn/seaborn_table.py#L681)):*
<details><summary><i>Previously, MichaelChristenson wrote…</i></summary><blockquote>

Change to "self.row_columns+=[item]"
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seaborngames/table/1)*

**Pull request closed without merging**
