### PR TITLE
6 fancy grid

### PR DESCRIPTION
**Pull request by MichaelChristenson**
This change is [Reviewable](https://reviewable.io/reviews/seaborngames/table/8)

### CODE REVIEW

**Comment by christensonb** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks broke.

---

*[seaborn/seaborn_table/seaborn_table.py, line 24 at r1](https://reviewable.io:443/reviews/seaborngames/table/8#-L3p99x9kK3Kv5S2yy_h:-L3p99x9kK3Kv5S2yy_i:b-x5pn45) ([raw file](https://github.com/seaborngames/table/blob/a35239719413023f036fe097abcf6e87acd3c579/seaborn/seaborn_table/seaborn_table.py#L24)):*
> ```Python
> from functools import reduce
> 
> DELIM_TAGS = ['t', 'ti', 'tr', 'tl',
> ```

why do you need this

---

*[seaborn/seaborn_table/seaborn_table.py, line 30 at r1](https://reviewable.io:443/reviews/seaborngames/table/8#-L3p98ZWj7uO8eRhFiKS:-L3p98ZWj7uO8eRhFiKT:b-x5pn45) ([raw file](https://github.com/seaborngames/table/blob/a35239719413023f036fe097abcf6e87acd3c579/seaborn/seaborn_table/seaborn_table.py#L30)):*
> ```Python
>               'iv', 'ih', 'ii', 'imi']
> 
> DIV_DELIMS = {"top": ['tl', 'ti', 't', 'tr'],
> ```

why do you need this

---

*[seaborn/seaborn_table/seaborn_table.py, line 35 at r1](https://reviewable.io:443/reviews/seaborngames/table/8#-L3p7an_SgHcp8MGStsL:-L3p7an_SgHcp8MGStsM:b-ssxuzj) ([raw file](https://github.com/seaborngames/table/blob/a35239719413023f036fe097abcf6e87acd3c579/seaborn/seaborn_table/seaborn_table.py#L35)):*
> ```Python
>              "btm": ['bl', 'bi', 'b', 'br']}
> 
> FANCY = {'t':'═', 'ti':'╤', 'tr':'╕', 'tl':'╒',
> ```

These variables should be in the class

---

*[seaborn/seaborn_table/seaborn_table.py, line 273 at r1](https://reviewable.io:443/reviews/seaborngames/table/8#-L3p7mLvvr3ZPFzDzUWH:-L3p7mLvvr3ZPFzDzUWI:bcs86m2) ([raw file](https://github.com/seaborngames/table/blob/a35239719413023f036fe097abcf6e87acd3c579/seaborn/seaborn_table/seaborn_table.py#L273)):*
> ```Python
>                     columns=None, key_on=None):
>         """
>         This will convert a csv file or csv text into a seaborn table
> ```

s/csv/grid

---

*[seaborn/seaborn_table/seaborn_table.py, line 283 at r1](https://reviewable.io:443/reviews/seaborngames/table/8#-L3p7xmUKRA5u98Q8Kok:-L3p7xmV2k3SN31voNd7:btv3s06) ([raw file](https://github.com/seaborngames/table/blob/a35239719413023f036fe097abcf6e87acd3c579/seaborn/seaborn_table/seaborn_table.py#L283)):*
> ```Python
> 
>         for tag in DELIM_TAGS:
>             delim[tag] = delim[tag] if tag in delim.keys() else FANCY[tag]
> ```

just put FANCY in the class and use self.FANCY

---

*[seaborn/seaborn_table/seaborn_table.py, line 491 at r1](https://reviewable.io:443/reviews/seaborngames/table/8#-L3p8Y1XkT9joPm6k9D4:-L3p8Y1XkT9joPm6k9D5:b-jmxj49) ([raw file](https://github.com/seaborngames/table/blob/a35239719413023f036fe097abcf6e87acd3c579/seaborn/seaborn_table/seaborn_table.py#L491)):*
> ```Python
>         :param deliminator: dict of deliminators, defaults to 
>                             obj_to_str's method:
>             ['t']:      top edge
> ```

change 't' to 'top edge' and do this for all the keys then remove this comment

---

*[seaborn/seaborn_table/seaborn_table.py, line 529 at r1](https://reviewable.io:443/reviews/seaborngames/table/8#-L3p9nDXHAFcczaXSRE8:-L3p9nDXHAFcczaXSRE9:b-vkxh89) ([raw file](https://github.com/seaborngames/table/blob/a35239719413023f036fe097abcf6e87acd3c579/seaborn/seaborn_table/seaborn_table.py#L529)):*
> ```Python
>         grid_row={}
> 
>         for key in DIV_DELIMS.keys():
> ```

replace this with for row in ['top', 'divide', 'middle', 'bottom']

---

*[seaborn/seaborn_table/seaborn_table.py, line 530 at r1](https://reviewable.io:443/reviews/seaborngames/table/8#-L3pA5STyq8p91xHdHn0:-L3pA5STyq8p91xHdHn1:b-qdqktg) ([raw file](https://github.com/seaborngames/table/blob/a35239719413023f036fe097abcf6e87acd3c579/seaborn/seaborn_table/seaborn_table.py#L530)):*
> ```Python
> 
>         for key in DIV_DELIMS.keys():
>             draw = DIV_DELIMS[key]
> ```

replace with for col in ['left', 'edge','intersecti','right'] 

then 
key = f"{row} {col}"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seaborngames/table/8)*

**Comment by MichaelChristenson** [comment]
*[seaborn/seaborn_table/seaborn_table.py, line 24 at r1](https://reviewable.io:443/reviews/seaborngames/table/8#-L3p99x9kK3Kv5S2yy_h:-L3yFpkhFZQoEYCeTzX3:b3wmnws) ([raw file](https://github.com/seaborngames/table/blob/a35239719413023f036fe097abcf6e87acd3c579/seaborn/seaborn_table/seaborn_table.py#L24)):*
<details><summary><i>Previously, christensonb (Ben Christenson) wrote…</i></summary><blockquote>

why do you need this
</blockquote></details>

It has been attended to; all usages have been replaced with either FANCY.keys() or grid_delims.keys()

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seaborngames/table/8)*

**Comment by MichaelChristenson** [comment]
*[seaborn/seaborn_table/seaborn_table.py, line 30 at r1](https://reviewable.io:443/reviews/seaborngames/table/8#-L3p98ZWj7uO8eRhFiKS:-L3yFzhP-yeCJ7j8s-NY:bomhqz4) ([raw file](https://github.com/seaborngames/table/blob/a35239719413023f036fe097abcf6e87acd3c579/seaborn/seaborn_table/seaborn_table.py#L30)):*
<details><summary><i>Previously, christensonb (Ben Christenson) wrote…</i></summary><blockquote>

why do you need this
</blockquote></details>

To easily compartmentalize the four different horizontal divisions; see row 524 (for key in self.DIV_DELIMS.keys():) This expedites rows 524-530

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seaborngames/table/8)*

**Comment by MichaelChristenson** [comment]
*[seaborn/seaborn_table/seaborn_table.py, line 529 at r1](https://reviewable.io:443/reviews/seaborngames/table/8#-L3p9nDXHAFcczaXSRE8:-L3yJfD6shWZu-IVSEzg:b-1kql8x) ([raw file](https://github.com/seaborngames/table/blob/a35239719413023f036fe097abcf6e87acd3c579/seaborn/seaborn_table/seaborn_table.py#L529)):*
<details><summary><i>Previously, christensonb (Ben Christenson) wrote…</i></summary><blockquote>

replace this with for row in ['top', 'divide', 'middle', 'bottom']
</blockquote></details>

Compromised: DIV_DELIMS renamed div_delims and moved into function block. Previous solution incompatible with delimiter naming schema.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seaborngames/table/8)*

**Comment by MichaelChristenson** [comment]
*[seaborn/seaborn_table/seaborn_table.py, line 530 at r1](https://reviewable.io:443/reviews/seaborngames/table/8#-L3pA5STyq8p91xHdHn0:-L3yLGraMCQs1EhYHBsI:brr096n) ([raw file](https://github.com/seaborngames/table/blob/a35239719413023f036fe097abcf6e87acd3c579/seaborn/seaborn_table/seaborn_table.py#L530)):*
<details><summary><i>Previously, christensonb (Ben Christenson) wrote…</i></summary><blockquote>

replace with for col in ['left', 'edge','intersecti','right'] 

then 
key = f"{row} {col}"

</blockquote></details>

As with comment on line 529

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seaborngames/table/8)*

**Comment by christensonb** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks broke.

---

*[seaborn/seaborn_table/seaborn_table.py, line 529 at r1](https://reviewable.io:443/reviews/seaborngames/table/8#-L4UB9L6dME4H4-Ta_0n:-L4UB9L7iM4SVKD9xPaO:b2lvkrm) ([raw file](https://github.com/seaborngames/table/blob/a35239719413023f036fe097abcf6e87acd3c579/seaborn/seaborn_table/seaborn_table.py#L529)):*
> ```Python
>         grid_row={}
> 
>         for key in DIV_DELIMS.keys():
> ```

how do you know the order of the keys?

---

*[seaborn/seaborn_table/seaborn_table.py, line 40 at r2](https://reviewable.io:443/reviews/seaborngames/table/8#-L4UAk_XqmKl8nW09gXZ:-L4UAk_XqmKl8nW09gX_:b-og46hq) ([raw file](https://github.com/seaborngames/table/blob/6b9d1337a35ce0051fadbfc10a59c55cdf9f43ad/seaborn/seaborn_table/seaborn_table.py#L40)):*
> ```Python
> 
>     def __init__(self, table=None, columns=None, row_columns=None, tab=None,
>                  key_on=None, deliminator=None, grid_delims = {}):
> ```

never ever put a container class as a default value.

Plus you don' t need to pass this in, it will never really be overloaded, and if it is they can just subclass.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seaborngames/table/8)*

**Comment by christensonb** [comment]
You need to doc changelog

---

Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/seaborngames/table/8#-:-L5P6Duq4KoOXWsSAMgG:b-uh3qht)*

**Comment by christensonb** [comment]
I get the following error when pip install in debug mode
python -c "from seaborn.seaborn_table import SeabornTable"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: bad magic number in 'seaborn': b'\x03\xf3\r\n'

---

Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/seaborngames/table/8#-:-L5P6XStKgs5RaktPjt9:bv7hcvi)*

**Comment by MichaelChristenson** [comment]
*[seaborn/seaborn_table/seaborn_table.py, line 35 at r1](https://reviewable.io:443/reviews/seaborngames/table/8#-L3p7an_SgHcp8MGStsL:-L5_nNBTJnQfOQ91Nocg:b-896fix) ([raw file](https://github.com/seaborngames/table/blob/a35239719413023f036fe097abcf6e87acd3c579/seaborn/seaborn_table/seaborn_table.py#L35)):*
<details><summary><i>Previously, christensonb (Ben Christenson) wrote…</i></summary><blockquote>

These variables should be in the class
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seaborngames/table/8)*

**Comment by MichaelChristenson** [comment]
*[seaborn/seaborn_table/seaborn_table.py, line 40 at r2](https://reviewable.io:443/reviews/seaborngames/table/8#-L4UAk_XqmKl8nW09gXZ:-L5_nOs_7BLVCRgWP_5_:b-896fix) ([raw file](https://github.com/seaborngames/table/blob/6b9d1337a35ce0051fadbfc10a59c55cdf9f43ad/seaborn/seaborn_table/seaborn_table.py#L40)):*
<details><summary><i>Previously, christensonb (Ben Christenson) wrote…</i></summary><blockquote>

never ever put a container class as a default value.

Plus you don' t need to pass this in, it will never really be overloaded, and if it is they can just subclass.


</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seaborngames/table/8)*

**Comment by MichaelChristenson** [comment]
*[seaborn/seaborn_table/seaborn_table.py, line 273 at r1](https://reviewable.io:443/reviews/seaborngames/table/8#-L3p7mLvvr3ZPFzDzUWH:-L5_nfS52E2cfeE8pG8j:b-896fix) ([raw file](https://github.com/seaborngames/table/blob/a35239719413023f036fe097abcf6e87acd3c579/seaborn/seaborn_table/seaborn_table.py#L273)):*
<details><summary><i>Previously, christensonb (Ben Christenson) wrote…</i></summary><blockquote>

s/csv/grid
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seaborngames/table/8)*

**Comment by MichaelChristenson** [comment]
*[seaborn/seaborn_table/seaborn_table.py, line 283 at r1](https://reviewable.io:443/reviews/seaborngames/table/8#-L3p7xmUKRA5u98Q8Kok:-L5_o-kHnah08YpO6a0u:b-896fix) ([raw file](https://github.com/seaborngames/table/blob/a35239719413023f036fe097abcf6e87acd3c579/seaborn/seaborn_table/seaborn_table.py#L283)):*
<details><summary><i>Previously, christensonb (Ben Christenson) wrote…</i></summary><blockquote>

just put FANCY in the class and use self.FANCY
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seaborngames/table/8)*

**Comment by MichaelChristenson** [comment]
*[seaborn/seaborn_table/seaborn_table.py, line 529 at r1](https://reviewable.io:443/reviews/seaborngames/table/8#-L4UB9L6dME4H4-Ta_0n:-L5_oAsuQBKtXXmue7Q7:bm2oxgh) ([raw file](https://github.com/seaborngames/table/blob/a35239719413023f036fe097abcf6e87acd3c579/seaborn/seaborn_table/seaborn_table.py#L529)):*
<details><summary><i>Previously, christensonb (Ben Christenson) wrote…</i></summary><blockquote>

how do you know the order of the keys?
</blockquote></details>

Order is irrelevant; I just need to make sure this is executed for each key.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seaborngames/table/8)*

**Pull request closed without merging**
