### PR TITLE
Dict row column

### PR DESCRIPTION
**Pull request by christensonb**

### CODE REVIEW

**Comment by MichaelChristenson** [comment]
*[setup.py, line 11 at r2](https://reviewable.io:443/reviews/seaborngames/table/2#-L20Ull6e835EDB_-qW0:-L20Ull6e835EDB_-qW1:bmkxjlq) ([raw file](https://github.com/seaborngames/table/blob/731a9175ba1550e4c24f90647ac9d6262f4ab0c0/setup.py#L11)):*
> ```Python
>     author='Ben Christenson',
>     author_email='Python@BenChristenson.com',
>     url='https://github.com/orgs/SeabornGames/SeabornTable',
> ```

'/orgs' is unnecessary for the url

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seaborngames/table/2)*

**Comment by MichaelChristenson** [comment]
*[seaborn/seaborn_table.py, line 131 at r2](https://reviewable.io:443/reviews/seaborngames/table/2#-L20Xd0SB5nfXadE4bwB:-L20Xd0SB5nfXadE4bwC:b4750mv) ([raw file](https://github.com/seaborngames/table/blob/731a9175ba1550e4c24f90647ac9d6262f4ab0c0/seaborn/seaborn_table.py#L131)):*
> ```Python
> 
>         elif isinstance(list_[0], (list, tuple)):
>             row_columns = row_columns or columns
> ```

Removal of or list_[0] seems dangerous; I don't see where columns is guaranteed to be defined

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seaborngames/table/2)*

**Comment by MichaelChristenson** [comment]
Reviewed 3 of 11 files at r1, 4 of 10 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/seaborngames/table/2)*

**Comment by christensonb** [comment]
Review status: 6 of 7 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[setup.py, line 11 at r2](https://reviewable.io:443/reviews/seaborngames/table/2#-L20Ull6e835EDB_-qW0:-L20wpS_jhDrc5jqdwOo:b-896fix) ([raw file](https://github.com/seaborngames/table/blob/731a9175ba1550e4c24f90647ac9d6262f4ab0c0/setup.py#L11)):*
<details><summary><i>Previously, MichaelChristenson wrote…</i></summary><blockquote>

'/orgs' is unnecessary for the url
</blockquote></details>

Done.

---

*[seaborn/seaborn_table.py, line 131 at r2](https://reviewable.io:443/reviews/seaborngames/table/2#-L20Xd0SB5nfXadE4bwB:-L20wwoYWVifbY7tRtrT:ba5yu0a) ([raw file](https://github.com/seaborngames/table/blob/731a9175ba1550e4c24f90647ac9d6262f4ab0c0/seaborn/seaborn_table.py#L131)):*
<details><summary><i>Previously, MichaelChristenson wrote…</i></summary><blockquote>

Removal of or list_[0] seems dangerous; I don't see where columns is guaranteed to be defined
</blockquote></details>

guaranteed from the function call

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seaborngames/table/2)*

**Comment by MichaelChristenson** [comment]
:lgtm:

---

Review status: 3 of 8 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/seaborngames/table/2#-:-L219oJI-yfyK9R3Mgp_:bnfp4nl)*

**Pull request merged**
